export EDITOR="nvim"
export GOPATH="$(go env GOPATH)"
export PATH="${PATH}:${GOPATH}/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/share/bob/nvim-bin"
export PATH="$PATH:$HOME/.local/share/coursier/bin"
export PATH="$PATH:$HOME/.cargo/bin"
